#!/usr/bin/env bash

set -euo pipefail

print_help() {
    echo "Installs latest version of clj-jdbc. Installation directory defaults to /usr/local/bin."
    echo -e
    echo "Usage:"
    echo "installer.sh [<dir>]"
    exit 1
}

default_install_dir="/usr/local/bin"
install_dir=$default_install_dir
install_dir_opt=${1:-}
if [ "$install_dir_opt" ]; then
    install_dir="$install_dir_opt"
fi

download_dir=/tmp

latest_release="$(curl -sL https://raw.githubusercontent.com/borkdude/clj-jdbc/master/resources/CLJ-JDBC_RELEASED_VERSION)"

case "$(uname -s)" in
    Linux*)     platform=linux;;
    Darwin*)    platform=macos;;
esac

download_url="https://github.com/borkdude/clj-jdbc/releases/download/v$latest_release/clj-jdbc-$latest_release-$platform-amd64.zip"

cd "$download_dir"
echo -e "Downloading $download_url."
curl -o "clj-jdbc-$latest_release-$platform-amd64.zip" -sL "https://github.com/borkdude/clj-jdbc/releases/download/v$latest_release/clj-jdbc-$latest_release-$platform-amd64.zip"
unzip -qqo "clj-jdbc-$latest_release-$platform-amd64.zip"
rm "clj-jdbc-$latest_release-$platform-amd64.zip"

cd "$install_dir"
if [ -f clj-jdbc ]; then
    echo "Moving $install_dir/bb to $install_dir/bb.old"
fi

mv -f "$download_dir/bb" "$PWD/bb"

echo "Successfully installed bb in $install_dir."
