#!/usr/bin/env bash

rm -rf /tmp/cljdoc
mkdir -p /tmp/cljdoc
version=$(cat resources/CLJ-JDBC_VERSION)

echo "---- cljdoc preview: installing jar in local repo"
lein install

echo "---- cljdoc preview: ingesting clj-jdbc"
docker run --rm -v "$PWD:/clj-jdbc" \
       -v "$HOME/.m2:/root/.m2" -v /tmp/cljdoc:/app/data --entrypoint "clojure" \
       cljdoc/cljdoc -A:cli ingest -p borkdude/clj-jdbc -v "$version" \
       --git /clj-jdbc

echo "---- cljdoc preview: starting server on port 8000"
docker run --rm -p 8000:8000 -v /tmp/cljdoc:/app/data cljdoc/cljdoc
# go directly to http://localhost:8000/d/borkdude/clj-jdbc/0.0.10-SNAPSHOT, not via the search
