#!/usr/bin/env bash

set -eo pipefail
CLJ-JDBC_PRELOADS=""
CLJ-JDBC_CLASSPATH=""
echo "running tests part 1"
lein test "$@"

CLJ-JDBC_PRELOADS='(defn __bb__foo [] "foo") (defn __bb__bar [] "bar")'
CLJ-JDBC_PRELOADS_TEST=true
echo "running tests part 2"
lein test :only clj-jdbc.main-test/preloads-test

CLJ-JDBC_PRELOADS="(require '[env-ns])"
CLJ-JDBC_CLASSPATH_TEST=true
CLJ-JDBC_CLASSPATH="test-resources/clj-jdbc/src_for_classpath_test/env"
echo "running tests part 3"
lein test :only clj-jdbc.classpath-test/classpath-env-test
