#!/usr/bin/env bash

set -eo pipefail

export CLJ-JDBC_CLASSPATH="$(clojure -Sdeps '{:deps {clojure-csv {:mvn/version "RELEASE"}}}' -Spath)"

if [ "$CLJ-JDBC_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

$BB_CMD -e "
(require '[clojure-csv.core :as csv])
(prn (csv/write-csv (csv/parse-csv \"a,b,c\n1,2,3\")))
"
